# Generated by Django 5.2.9 on 2026-01-15 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_profile_fields"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
