# Generated by Django 5.2.9

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("stripe_payment_method_id", models.CharField(blank=True, max_length=255, unique=True)),
                ("type", models.CharField(default="card", max_length=20)),
                ("last4", models.CharField(blank=True, max_length=4)),
                ("brand", models.CharField(blank=True, max_length=20)),
                ("exp_month", models.IntegerField(blank=True, null=True)),
                ("exp_year", models.IntegerField(blank=True, null=True)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_methods",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Method",
                "verbose_name_plural": "Payment Methods",
                "db_table": "billing_payment_method",
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("stripe_invoice_id", models.CharField(blank=True, max_length=255, unique=True)),
                ("amount_due", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("amount_paid", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("currency", models.CharField(default="usd", max_length=3)),
                ("status", models.CharField(default="draft", max_length=20)),
                ("invoice_pdf_url", models.URLField(blank=True, max_length=500)),
                ("period_start", models.DateTimeField(blank=True, null=True)),
                ("period_end", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice",
                "verbose_name_plural": "Invoices",
                "db_table": "billing_invoice",
                "ordering": ["-created_at"],
            },
        ),
    ]
