# Generated by Django 5.2.9 on 2026-01-02 14:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("amazon_ads", "0001_initial"),
        ("amazon_auth", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutopilotGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "goal_type",
                    models.CharField(
                        choices=[
                            ("profit", "Maximize Profit"),
                            ("growth", "Maximize Growth"),
                            ("rank", "Improve Ranking"),
                            ("acos", "Target ACOS"),
                            ("roas", "Target ROAS"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "target_acos",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Target ACOS percentage (0-100)",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                (
                    "target_roas",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Target ROAS ratio",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                ("applies_to_all_campaigns", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="autopilot_goals",
                        to="amazon_auth.amazonaccount",
                    ),
                ),
                (
                    "campaigns",
                    models.ManyToManyField(
                        blank=True, related_name="autopilot_goals", to="amazon_ads.campaign"
                    ),
                ),
            ],
            options={
                "verbose_name": "Autopilot Goal",
                "verbose_name_plural": "Autopilot Goals",
                "db_table": "autopilot_goal",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AutomationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("keyword_bid", "Keyword Bid Adjustment"),
                            ("keyword_pause", "Pause Keyword"),
                            ("keyword_enable", "Enable Keyword"),
                            ("campaign_budget", "Campaign Budget Adjustment"),
                            ("campaign_pause", "Pause Campaign"),
                            ("negative_keyword", "Add Negative Keyword"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(default=0, help_text="Higher priority rules run first"),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "condition_metric",
                    models.CharField(
                        choices=[
                            ("spend", "Spend"),
                            ("sales", "Sales"),
                            ("acos", "ACOS"),
                            ("roas", "ROAS"),
                            ("clicks", "Clicks"),
                            ("impressions", "Impressions"),
                            ("ctr", "CTR"),
                            ("conversions", "Conversions"),
                            ("orders", "Orders"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "condition_operator",
                    models.CharField(
                        choices=[
                            ("gt", "Greater Than"),
                            ("gte", "Greater Than or Equal"),
                            ("lt", "Less Than"),
                            ("lte", "Less Than or Equal"),
                            ("eq", "Equals"),
                            ("ne", "Not Equals"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "condition_value",
                    models.DecimalField(
                        decimal_places=4, help_text="Threshold value for condition", max_digits=10
                    ),
                ),
                (
                    "lookback_days",
                    models.IntegerField(
                        default=7,
                        help_text="Number of days to look back for metrics",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(90),
                        ],
                    ),
                ),
                (
                    "action_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Action value (e.g., new bid amount, budget amount)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "action_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Percentage change (e.g., -10 for 10% decrease)",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("-100")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                (
                    "max_bid_change_percent",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("20"),
                        help_text="Maximum bid change percentage per day",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                (
                    "min_bid",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Minimum bid amount",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                (
                    "max_bid",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum bid amount",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_executed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="autopilot.autopilotgoal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Automation Rule",
                "verbose_name_plural": "Automation Rules",
                "db_table": "autopilot_rule",
                "ordering": ["-priority", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SafetyLimit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "max_bid_changes_per_day",
                    models.IntegerField(default=50, help_text="Max bid changes per day"),
                ),
                (
                    "max_budget_changes_per_day",
                    models.IntegerField(default=10, help_text="Max budget changes per day"),
                ),
                (
                    "max_campaign_pauses_per_day",
                    models.IntegerField(default=5, help_text="Max campaign pauses per day"),
                ),
                (
                    "max_daily_budget_increase_percent",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("50"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                (
                    "max_daily_budget_decrease_percent",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("30"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True, help_text="Master switch to disable all automation"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="safety_limits",
                        to="amazon_auth.amazonaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Safety Limit",
                "verbose_name_plural": "Safety Limits",
                "db_table": "autopilot_safety_limit",
            },
        ),
        migrations.CreateModel(
            name="AutopilotExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("executed", "Executed"),
                            ("skipped", "Skipped"),
                            ("failed", "Failed"),
                            ("blocked", "Blocked by Safety"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(help_text="e.g., 'keyword', 'campaign'", max_length=50),
                ),
                (
                    "entity_id",
                    models.CharField(help_text="ID of the entity being modified", max_length=100),
                ),
                ("condition_met", models.BooleanField(default=False)),
                (
                    "metric_value",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
                ),
                (
                    "old_value",
                    models.CharField(blank=True, help_text="Value before change", max_length=255),
                ),
                (
                    "new_value",
                    models.CharField(blank=True, help_text="Value after change", max_length=255),
                ),
                ("reason", models.TextField(blank=True, help_text="Explanation of the decision")),
                ("safety_check_passed", models.BooleanField(default=True)),
                ("safety_reason", models.TextField(blank=True)),
                ("executed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="autopilot_executions",
                        to="amazon_auth.amazonaccount",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="autopilot.automationrule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Autopilot Execution",
                "verbose_name_plural": "Autopilot Executions",
                "db_table": "autopilot_execution",
                "ordering": ["-executed_at"],
                "indexes": [
                    models.Index(
                        fields=["account", "status", "executed_at"],
                        name="autopilot_e_account_231309_idx",
                    ),
                    models.Index(
                        fields=["rule", "executed_at"], name="autopilot_e_rule_id_5d1b37_idx"
                    ),
                ],
            },
        ),
    ]
