# Generated by Django 5.2.9 on 2026-02-06 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_managers"),
        ("autopilot", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutopilotPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("settings", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="autopilot_preference",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Autopilot Preference",
                "verbose_name_plural": "Autopilot Preferences",
                "db_table": "autopilot_preference",
            },
        ),
    ]
