# Generated by Django 5.2.9 on 2026-01-02 14:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("amazon_auth", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("campaign_id", models.CharField(db_index=True, max_length=100, unique=True)),
                ("portfolio_id", models.CharField(blank=True, max_length=100)),
                ("name", models.CharField(max_length=255)),
                (
                    "campaign_type",
                    models.CharField(
                        choices=[
                            ("sponsored_products", "Sponsored Products"),
                            ("sponsored_brands", "Sponsored Brands"),
                            ("sponsored_display", "Sponsored Display"),
                        ],
                        default="sponsored_products",
                        max_length=50,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("enabled", "Enabled"),
                            ("paused", "Paused"),
                            ("archived", "Archived"),
                        ],
                        default="enabled",
                        max_length=20,
                    ),
                ),
                (
                    "daily_budget",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                (
                    "bidding_strategy",
                    models.CharField(
                        choices=[
                            ("legacy_for_sales", "Legacy for Sales"),
                            ("auto_for_sales", "Auto for Sales"),
                            ("manual", "Manual"),
                        ],
                        default="manual",
                        max_length=50,
                    ),
                ),
                ("targeting_type", models.CharField(blank=True, max_length=50)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaigns",
                        to="amazon_auth.amazonaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Campaign",
                "verbose_name_plural": "Campaigns",
                "db_table": "amazon_ads_campaign",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AdGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("ad_group_id", models.CharField(db_index=True, max_length=100, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("enabled", "Enabled"),
                            ("paused", "Paused"),
                            ("archived", "Archived"),
                        ],
                        default="enabled",
                        max_length=20,
                    ),
                ),
                (
                    "default_bid",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ad_groups",
                        to="amazon_ads.campaign",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ad Group",
                "verbose_name_plural": "Ad Groups",
                "db_table": "amazon_ads_ad_group",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CampaignPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("impressions", models.IntegerField(default=0)),
                ("clicks", models.IntegerField(default=0)),
                (
                    "cost",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10),
                ),
                (
                    "sales",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10),
                ),
                ("orders", models.IntegerField(default=0)),
                ("units_sold", models.IntegerField(default=0)),
                (
                    "ctr",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
                ),
                (
                    "cpc",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
                ),
                (
                    "acos",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
                ),
                (
                    "roas",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
                ),
                (
                    "cvr",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_data",
                        to="amazon_ads.campaign",
                    ),
                ),
            ],
            options={
                "verbose_name": "Campaign Performance",
                "verbose_name_plural": "Campaign Performance",
                "db_table": "amazon_ads_campaign_performance",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Keyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("keyword_id", models.CharField(db_index=True, max_length=100, unique=True)),
                ("keyword_text", models.CharField(max_length=255)),
                (
                    "match_type",
                    models.CharField(
                        choices=[
                            ("exact", "Exact"),
                            ("phrase", "Phrase"),
                            ("broad", "Broad"),
                            ("negativeExact", "Negative Exact"),
                            ("negativePhrase", "Negative Phrase"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("enabled", "Enabled"),
                            ("paused", "Paused"),
                            ("archived", "Archived"),
                        ],
                        default="enabled",
                        max_length=20,
                    ),
                ),
                (
                    "bid",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "ad_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keywords",
                        to="amazon_ads.adgroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Keyword",
                "verbose_name_plural": "Keywords",
                "db_table": "amazon_ads_keyword",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="KeywordPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("impressions", models.IntegerField(default=0)),
                ("clicks", models.IntegerField(default=0)),
                (
                    "cost",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10),
                ),
                (
                    "sales",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10),
                ),
                ("orders", models.IntegerField(default=0)),
                (
                    "ctr",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
                ),
                (
                    "cpc",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
                ),
                (
                    "acos",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
                ),
                (
                    "roas",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "keyword",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_data",
                        to="amazon_ads.keyword",
                    ),
                ),
            ],
            options={
                "verbose_name": "Keyword Performance",
                "verbose_name_plural": "Keyword Performance",
                "db_table": "amazon_ads_keyword_performance",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="NegativeKeyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("keyword_id", models.CharField(db_index=True, max_length=100, unique=True)),
                ("keyword_text", models.CharField(max_length=255)),
                (
                    "match_type",
                    models.CharField(
                        choices=[
                            ("negativeExact", "Negative Exact"),
                            ("negativePhrase", "Negative Phrase"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("enabled", "Enabled"),
                            ("paused", "Paused"),
                            ("deleted", "Deleted"),
                        ],
                        default="enabled",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ad_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="negative_keywords",
                        to="amazon_ads.adgroup",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="negative_keywords",
                        to="amazon_ads.campaign",
                    ),
                ),
            ],
            options={
                "verbose_name": "Negative Keyword",
                "verbose_name_plural": "Negative Keywords",
                "db_table": "amazon_ads_negative_keyword",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SearchTerm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("query", models.CharField(db_index=True, max_length=500)),
                ("match_type", models.CharField(blank=True, max_length=20)),
                ("impressions", models.IntegerField(default=0)),
                ("clicks", models.IntegerField(default=0)),
                (
                    "cost",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10),
                ),
                (
                    "sales",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10),
                ),
                ("orders", models.IntegerField(default=0)),
                (
                    "acos",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
                ),
                (
                    "roas",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
                ),
                ("date", models.DateField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ad_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_terms",
                        to="amazon_ads.adgroup",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_terms",
                        to="amazon_ads.campaign",
                    ),
                ),
                (
                    "keyword",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_terms",
                        to="amazon_ads.keyword",
                    ),
                ),
            ],
            options={
                "verbose_name": "Search Term",
                "verbose_name_plural": "Search Terms",
                "db_table": "amazon_ads_search_term",
                "ordering": ["-date", "-cost"],
            },
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(fields=["account", "state"], name="amazon_ads__account_54bca0_idx"),
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(fields=["campaign_id"], name="amazon_ads__campaig_72d1de_idx"),
        ),
        migrations.AddIndex(
            model_name="adgroup",
            index=models.Index(fields=["campaign", "state"], name="amazon_ads__campaig_3cbd18_idx"),
        ),
        migrations.AddIndex(
            model_name="adgroup",
            index=models.Index(fields=["ad_group_id"], name="amazon_ads__ad_grou_047ccd_idx"),
        ),
        migrations.AddIndex(
            model_name="campaignperformance",
            index=models.Index(fields=["date", "campaign"], name="amazon_ads__date_09b0c5_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="campaignperformance",
            unique_together={("campaign", "date")},
        ),
        migrations.AddIndex(
            model_name="keyword",
            index=models.Index(fields=["ad_group", "state"], name="amazon_ads__ad_grou_6ced54_idx"),
        ),
        migrations.AddIndex(
            model_name="keyword",
            index=models.Index(fields=["keyword_id"], name="amazon_ads__keyword_94ebd4_idx"),
        ),
        migrations.AddIndex(
            model_name="keyword",
            index=models.Index(fields=["keyword_text"], name="amazon_ads__keyword_254a15_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="keywordperformance",
            unique_together={("keyword", "date")},
        ),
        migrations.AddIndex(
            model_name="searchterm",
            index=models.Index(fields=["date", "campaign"], name="amazon_ads__date_a181a3_idx"),
        ),
        migrations.AddIndex(
            model_name="searchterm",
            index=models.Index(fields=["query"], name="amazon_ads__query_8aa083_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="searchterm",
            unique_together={("query", "campaign", "ad_group", "date")},
        ),
    ]
