# Generated by Django 5.2.9 on 2026-01-02 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("amazon_ads", "0001_initial"),
        ("amazon_auth", "0001_initial"),
        ("amazon_sp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutoPauseRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("applies_to_all_products", models.BooleanField(default=False)),
                ("applies_to_all_campaigns", models.BooleanField(default=True)),
                (
                    "stock_threshold",
                    models.IntegerField(default=10, help_text="Pause when stock falls below this"),
                ),
                (
                    "auto_resume",
                    models.BooleanField(default=True, help_text="Resume when stock is restored"),
                ),
                (
                    "resume_threshold",
                    models.IntegerField(default=20, help_text="Resume when stock reaches this"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auto_pause_rules",
                        to="amazon_auth.amazonaccount",
                    ),
                ),
                (
                    "campaigns",
                    models.ManyToManyField(
                        related_name="auto_pause_rules", to="amazon_ads.campaign"
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(related_name="auto_pause_rules", to="amazon_sp.product"),
                ),
            ],
            options={
                "verbose_name": "Auto Pause Rule",
                "verbose_name_plural": "Auto Pause Rules",
                "db_table": "inventory_auto_pause_rule",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InventoryAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("low_stock", "Low Stock"),
                            ("out_of_stock", "Out of Stock"),
                            ("restocked", "Restocked"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("resolved", "Resolved"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("current_stock", models.IntegerField()),
                ("threshold", models.IntegerField()),
                ("message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_alerts",
                        to="amazon_auth.amazonaccount",
                    ),
                ),
                (
                    "campaigns_paused",
                    models.ManyToManyField(
                        blank=True, related_name="inventory_pause_alerts", to="amazon_ads.campaign"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_alerts",
                        to="amazon_sp.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventory Alert",
                "verbose_name_plural": "Inventory Alerts",
                "db_table": "inventory_alert",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["account", "status"], name="inventory_a_account_ca49a7_idx"
                    )
                ],
            },
        ),
    ]
