# Generated by Django 5.2.9 on 2026-01-02 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("amazon_auth", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("order_id", models.CharField(db_index=True, max_length=50, unique=True)),
                ("amazon_order_id", models.CharField(blank=True, max_length=50)),
                ("purchase_date", models.DateTimeField()),
                (
                    "order_status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Unshipped", "Unshipped"),
                            ("PartiallyShipped", "Partially Shipped"),
                            ("Shipped", "Shipped"),
                            ("Canceled", "Canceled"),
                            ("Unfulfillable", "Unfulfillable"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "fulfillment_channel",
                    models.CharField(
                        choices=[
                            ("MFN", "Merchant Fulfilled Network"),
                            ("AFN", "Amazon Fulfilled Network"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "order_total",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("ship_country", models.CharField(blank=True, max_length=2)),
                ("ship_city", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="amazon_auth.amazonaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
                "db_table": "amazon_sp_order",
                "ordering": ["-purchase_date"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "asin",
                    models.CharField(
                        db_index=True,
                        help_text="Amazon Standard Identification Number",
                        max_length=10,
                    ),
                ),
                ("sku", models.CharField(db_index=True, help_text="Seller SKU", max_length=255)),
                ("title", models.CharField(blank=True, max_length=500)),
                ("brand", models.CharField(blank=True, max_length=255)),
                (
                    "fulfillment_type",
                    models.CharField(
                        choices=[("FBA", "Fulfilled by Amazon"), ("FBM", "Fulfilled by Merchant")],
                        default="FBA",
                        max_length=10,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="amazon_auth.amazonaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "db_table": "amazon_sp_product",
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("asin", models.CharField(max_length=10)),
                ("sku", models.CharField(max_length=255)),
                ("title", models.CharField(blank=True, max_length=500)),
                ("quantity_ordered", models.IntegerField(default=1)),
                ("quantity_shipped", models.IntegerField(default=0)),
                (
                    "item_price",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "shipping_price",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "item_tax",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="amazon_sp.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_items",
                        to="amazon_sp.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Item",
                "verbose_name_plural": "Order Items",
                "db_table": "amazon_sp_order_item",
            },
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("available_quantity", models.IntegerField(default=0, help_text="Available units")),
                ("reserved_quantity", models.IntegerField(default=0, help_text="Reserved units")),
                ("inbound_quantity", models.IntegerField(default=0, help_text="Inbound units")),
                ("fba_available", models.IntegerField(default=0, help_text="FBA available units")),
                ("fba_reserved", models.IntegerField(default=0, help_text="FBA reserved units")),
                ("fba_inbound", models.IntegerField(default=0, help_text="FBA inbound units")),
                (
                    "low_stock_threshold",
                    models.IntegerField(default=10, help_text="Alert when stock falls below this"),
                ),
                ("is_low_stock", models.BooleanField(default=False)),
                ("date", models.DateField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_records",
                        to="amazon_sp.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventory",
                "verbose_name_plural": "Inventory",
                "db_table": "amazon_sp_inventory",
                "ordering": ["-date"],
            },
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["account", "order_status"], name="amazon_sp_o_account_256bf2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["purchase_date"], name="amazon_sp_o_purchas_f6c9f7_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["account", "asin"], name="amazon_sp_p_account_7b6a17_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["sku"], name="amazon_sp_p_sku_cdf21c_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="product",
            unique_together={("account", "asin")},
        ),
        migrations.AddIndex(
            model_name="inventory",
            index=models.Index(fields=["date", "product"], name="amazon_sp_i_date_e1be15_idx"),
        ),
        migrations.AddIndex(
            model_name="inventory",
            index=models.Index(fields=["is_low_stock"], name="amazon_sp_i_is_low__5019c1_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="inventory",
            unique_together={("product", "date")},
        ),
    ]
