# Generated by Django 5.2.9 on 2026-01-02 14:03

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("amazon_ads", "0001_initial"),
        ("amazon_auth", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailySummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("total_campaigns", models.IntegerField(default=0)),
                ("active_campaigns", models.IntegerField(default=0)),
                ("total_impressions", models.IntegerField(default=0)),
                ("total_clicks", models.IntegerField(default=0)),
                (
                    "total_cost",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10),
                ),
                (
                    "total_sales",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10),
                ),
                ("total_orders", models.IntegerField(default=0)),
                ("total_units_sold", models.IntegerField(default=0)),
                (
                    "overall_ctr",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
                ),
                (
                    "overall_cpc",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
                ),
                (
                    "overall_acos",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
                ),
                (
                    "overall_roas",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
                ),
                (
                    "overall_cvr",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_summaries",
                        to="amazon_auth.amazonaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Summary",
                "verbose_name_plural": "Daily Summaries",
                "db_table": "analytics_daily_summary",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(fields=["account", "date"], name="analytics_d_account_27f932_idx")
                ],
                "unique_together": {("account", "date")},
            },
        ),
        migrations.CreateModel(
            name="KeywordTrend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("week_start", models.DateField(db_index=True)),
                ("avg_impressions", models.IntegerField(default=0)),
                ("avg_clicks", models.IntegerField(default=0)),
                (
                    "avg_cost",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10),
                ),
                (
                    "avg_sales",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10),
                ),
                (
                    "avg_acos",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
                ),
                (
                    "avg_roas",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
                ),
                (
                    "impressions_trend",
                    models.CharField(blank=True, help_text="up/down/stable", max_length=20),
                ),
                ("cost_trend", models.CharField(blank=True, max_length=20)),
                ("sales_trend", models.CharField(blank=True, max_length=20)),
                ("acos_trend", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "keyword",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trends",
                        to="amazon_ads.keyword",
                    ),
                ),
            ],
            options={
                "verbose_name": "Keyword Trend",
                "verbose_name_plural": "Keyword Trends",
                "db_table": "analytics_keyword_trend",
                "ordering": ["-week_start"],
                "unique_together": {("keyword", "week_start")},
            },
        ),
    ]
