# Generated by Django 5.2.9 on 2026-01-02 14:03

import apps.amazon_auth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AmazonAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "account_name",
                    models.CharField(help_text="Friendly name for this account", max_length=255),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("advertiser", "Advertiser (Advertising API)"),
                            ("seller", "Seller (SP-API)"),
                            ("both", "Both"),
                        ],
                        default="both",
                        max_length=20,
                    ),
                ),
                (
                    "profile_id",
                    models.CharField(
                        blank=True, help_text="Amazon profile/advertiser ID", max_length=100
                    ),
                ),
                (
                    "seller_id",
                    models.CharField(blank=True, help_text="Amazon Seller ID", max_length=100),
                ),
                (
                    "marketplace_id",
                    models.CharField(blank=True, help_text="Marketplace ID", max_length=100),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_connected", models.BooleanField(default=False)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amazon_accounts",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Amazon Account",
                "verbose_name_plural": "Amazon Accounts",
                "db_table": "amazon_auth_account",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AmazonAdsAuth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "access_token",
                    apps.amazon_auth.models.EncryptedTextField(help_text="Encrypted access token"),
                ),
                (
                    "refresh_token",
                    apps.amazon_auth.models.EncryptedTextField(help_text="Encrypted refresh token"),
                ),
                ("token_type", models.CharField(default="bearer", max_length=50)),
                ("expires_at", models.DateTimeField(help_text="When the access token expires")),
                ("scope", models.TextField(blank=True, help_text="OAuth scopes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ads_auth",
                        to="amazon_auth.amazonaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Amazon Ads Auth",
                "verbose_name_plural": "Amazon Ads Auth",
                "db_table": "amazon_auth_ads",
            },
        ),
        migrations.CreateModel(
            name="AmazonSPAuth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "access_token",
                    apps.amazon_auth.models.EncryptedTextField(help_text="Encrypted access token"),
                ),
                (
                    "refresh_token",
                    apps.amazon_auth.models.EncryptedTextField(help_text="Encrypted refresh token"),
                ),
                ("token_type", models.CharField(default="bearer", max_length=50)),
                ("expires_at", models.DateTimeField(help_text="When the access token expires")),
                ("client_id", models.CharField(blank=True, max_length=255)),
                (
                    "client_secret",
                    apps.amazon_auth.models.EncryptedTextField(
                        blank=True, help_text="Encrypted client secret"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sp_auth",
                        to="amazon_auth.amazonaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Amazon SP-API Auth",
                "verbose_name_plural": "Amazon SP-API Auth",
                "db_table": "amazon_auth_sp",
            },
        ),
    ]
