# Generated by Django 5.2.9 on 2026-01-02 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("amazon_auth", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("keyword_bid_update", "Keyword Bid Update"),
                            ("keyword_pause", "Keyword Pause"),
                            ("keyword_enable", "Keyword Enable"),
                            ("campaign_budget_update", "Campaign Budget Update"),
                            ("campaign_pause", "Campaign Pause"),
                            ("campaign_enable", "Campaign Enable"),
                            ("negative_keyword_add", "Add Negative Keyword"),
                            ("negative_keyword_remove", "Remove Negative Keyword"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(help_text="e.g., 'keyword', 'campaign'", max_length=50),
                ),
                ("entity_id", models.CharField(help_text="ID of the entity", max_length=100)),
                (
                    "old_value",
                    models.CharField(blank=True, help_text="Value before change", max_length=255),
                ),
                (
                    "new_value",
                    models.CharField(blank=True, help_text="Value after change", max_length=255),
                ),
                ("reason", models.TextField(help_text="Explanation of why the change was made")),
                (
                    "rule_id",
                    models.IntegerField(
                        blank=True, help_text="ID of automation rule if applicable", null=True
                    ),
                ),
                (
                    "execution_id",
                    models.IntegerField(
                        blank=True, help_text="ID of autopilot execution if applicable", null=True
                    ),
                ),
                ("is_automated", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="amazon_auth.amazonaccount",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "db_table": "audit_logs_audit_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["account", "created_at"], name="audit_logs__account_f56f99_idx"
                    ),
                    models.Index(
                        fields=["action", "created_at"], name="audit_logs__action_31299f_idx"
                    ),
                    models.Index(
                        fields=["entity_type", "entity_id"], name="audit_logs__entity__bd2598_idx"
                    ),
                ],
            },
        ),
    ]
